version: '3.6'

services:
  app:
    build:
        context: .
        dockerfile: dev.Dockerfile
    ports:
      - "3010:3010"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "/workspace/build/server/server.js"
    volumes:
      - "./:/workspace"
